FROM node:18-alpine3.17 as build
WORKDIR /usr/src/bot

RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers git python3 make g++

COPY package*.json ./
RUN npm install
RUN npm i -g tsc-watch

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/entrypoint-dev.sh ./
COPY ./docker/wait-for-postgres.js ./

ENTRYPOINT /usr/src/bot/entrypoint-dev.sh
