FROM node:18-alpine3.14 as build
WORKDIR /usr/src/bot

RUN apk update && \
    apk add --no-cache postgresql gcc musl-dev linux-headers git python3 make g++

COPY package*.json ./
RUN npm install
RUN npm i -g nodemon

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/entrypoint-dev.sh /

ENTRYPOINT /entrypoint-dev.sh
