FROM oven/bun:1-alpine as build
WORKDIR /usr/src/bot

RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers git python3 make g++

COPY package*.json ./
RUN bun install

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/entrypoint-dev.sh ./
COPY ./docker/wait-for-postgres.js ./

ENTRYPOINT /usr/src/bot/entrypoint-dev.sh
